apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hanna-app
spec:
  project: default
  source:
    repoURL: "https://github.com/hannamatheos/argocd"
    targetRevision: main
    path: . (depends on which folder it's in)
  destination:
    server: https://kubernetes.default.svc
    namespace: hanna-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
